#!/bin/sh

# Copyright (c) [Fendy/WHU] [2025-2026]
# Licensed under the MIT License (the "MIT License");
# You may obtain a copy of the MIT License at:
#   https://opensource.org/licenses/MIT

set -eu

# $1 -- the path of zip file
# $2 -- the path of output (/output/xx-parser_name/xxx.zip/)

filename=$(basename "$1")
src_dir="/workspace/src"
executable="$src_dir/unzipada"

find . -name "*.gcda" -delete
"$executable" -o "$1" -d "$2"

/workspace/coverage.sh "$src_dir" "$filename" "$2/.."
