#!/bin/sh

# Copyright (c) [Fendy/WHU] [2025-2026]
# Licensed under the MIT License (the "MIT License");
# You may obtain a copy of the MIT License at:
#   https://opensource.org/licenses/MIT

set -eu

# $1 -- the path of zip file
# $2 -- the path of output **directory** (without sub directory)

filename=$(basename "$1")
src_dir="/workspace/unzip60"
executable="$src_dir/unzip"
"$executable" -t "$1"
"$executable" -o "$1" -d "$2"

/workspace/coverage.sh "$src_dir" "$filename" "$2/.."

